---
title: "JSC370 Final Project"
author: "Tyler-CY"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Final Project website.

```{r echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE)
library(dplyr)
library(plotly)
source('process_COVID_data.R')
```


```{r echo=FALSE}
p1_scatter <- cv_states_today %>%
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ", deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

# filter out "District of Columbia"
cv_states_today_scatter <- cv_states_today %>% filter(state!="District of Columbia")

p2_scatter <- cv_states_today_scatter %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

```



```{r echo=FALSE}
plt_smooth_1 <- ggplot(
  cv_states_today,
  aes(x = pop_density, y = newdeathsper100k)
) +
  theme_minimal() +
  geom_smooth() +
  geom_point(aes(colour = state, size = population)) +
  scale_x_continuous(
    trans = "log", 
    breaks = c(1, 10, 100, 1000, 10000),
    labels = c(1, 10, 100, 1000, 10000)
  )
```

```{r echo=FALSE}
# removing District of Columbia without log transformation
plt_smooth_2 <- ggplot(
  cv_states_today |> filter(state != "District of Columbia"),
  aes(x = pop_density, y = newdeathsper100k)
) +
  theme_minimal() +
  geom_smooth() +
  geom_point(aes(colour = state, size = population)) 

```






## Showcasing plots {.tabset}

### Figure 1

```{r echo=FALSE}
p1_scatter
```

### Figure 2

```{r echo=FALSE}
p2_scatter
```

### Figure 3

```{r echo=FALSE}
ggplotly(plt_smooth_1)
```

### Figure 4
```{r echo=FALSE}
ggplotly(plt_smooth_2)
```

{-}

## Conclusion

This is a conclusion.




